baseurl = "/"
languageCode = "en-us"
title = "mlr3 gallery"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"

[permalinks]
    post = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "mlr3"
    url = "https://mlr3.mlr-org.com"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mlr-org/mlr3gallery"

[params]
    customCSS = ["https://fonts.googleapis.com/css?family=Fira+Code&display=swap", "css/custom.css"]
    description = "Case studies using mlr3"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.18.1"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    #highlightjsTheme = "tomorrow-night-eighties"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.7"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "mlr logo"
